### ISSUE TITLE
NoSuchMethodError for Preconditions.checkState after upgrading Gradle plugin from 5.2.3 to 6.5.1

### ISSUE THREAD

**Issue by jeremylong** [dependency-check/DependencyCheck-fork#3927]
The repository has moved to https://github.com/dependency-check/DependencyCheck

The issue you are looking for can be found here: [issues#3927](https://github.com/dependency-check/DependencyCheck/issues/3927).
